# Use the specified base image
FROM runpod/stable-diffusion:web-automatic-6.0.0

RUN \
  pip3 install imageio moviepy opencv-python ftfy datasets scikit-image && \
  pip3 install git+https://github.com/openai/CLIP.git --no-deps


# Clone the required repositories and install dependencies
RUN git clone https://github.com/ntc-ai/conceptmod /conceptmod &&\
    cd /conceptmod && \
    git clone https://github.com/THUDM/ImageReward && \
    cd ImageReward && \
    cd ..

COPY smile.safetensors /stable-diffusion-webui/models/Lora/smile.safetensors

# Set the working directory
WORKDIR /conceptmod

RUN echo 'echo "Installing dependencies..."' > ~/.bashrc
# Create the installdeps.sh script and add it to .bashrc
RUN echo 'pip install --upgrade pip' > /conceptmod/installdeps.sh && \
    echo 'pip3 install imageio moviepy opencv-python ftfy datasets scikit-image' >> /conceptmod/installdeps.sh && \
    echo 'pip3 install git+https://github.com/openai/CLIP.git --no-deps' >> /conceptmod/installdeps.sh && \
    echo 'cd /conceptmod/ImageReward' >> /conceptmod/installdeps.sh && \
    echo 'python setup.py develop > /dev/null 2>&1' >> /conceptmod/installdeps.sh && \
    echo 'source /conceptmod/installdeps.sh > /dev/null && 2>&1 cd /conceptmod' >> ~/.bashrc

RUN echo 'echo " - - - - - - "' >> /root/.bashrc

RUN echo 'echo "Welcome to NTC-AI lora animator."' >> /root/.bashrc
RUN echo 'echo "Comment on one of the models if you have a problem civit.ai/user/ntc"' >> /root/.bashrc
RUN echo 'echo "Example command: python3 lora_anim.py -s 0 -e 2 -l smile -lp \", smile\""' >> /root/.bashrc
RUN echo 'echo ""' >> /root/.bashrc
RUN echo 'echo "Note: smile.safetensors is included. You need to upload other Loras into /stable-diffusion-webui/models/Lora. Use runpodctl"' >> /root/.bashrc
RUN echo 'echo "If the lora is not found, it will result in a static image. See the container logs for automatic1111 debug logs."' >> /root/.bashrc
RUN echo 'echo "This is using the default sd15. To use your own model, upload a model using runpodctl to /stable-diffusion-webui/models/Stable-diffusion then select it within a111 web ui (port 3000)."' >> /root/.bashrc
RUN echo 'echo ""' >> /root/.bashrc

# Update the relauncher.py script to add --api flag
RUN sed -i 's/launch_string = "\/workspace\/stable-diffusion-webui\/webui.sh -f"/launch_string = "\/workspace\/stable-diffusion-webui\/webui.sh -f --api"/' /stable-diffusion-webui/relauncher.py
EXPOSE 3000
# Run the anim.sh script
CMD ["bash", "/start.sh"]
